config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  root 'jobs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where(is_online: true).order(publish_date: :desc).page(params[:page]).per(5)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :content, :publish_date, :is_online)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :job_content, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date, id: :job_publish_date %>
  </div>

  <div class="field">
    <%= form.label :is_online %>
    <%= form.check_box :is_online, id: :job_is_online %>
  </div>

  <%= form.submit 'Submit', class: "btn btn-info" %>
<% end %>
<br>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job, class: "btn btn-primary" %> |
<%= link_to 'Back', jobs_path, class: "btn btn-secondary" %>

app/views/jobs/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb bg-white pl-0 pb-1 mb-0">
    <li class="breadcrumb-item"><a href="#">首頁</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="">徵才資訊</a></li>
  </ol>
</nav>
<div class="job_list">
<% @jobs.each do |job| %>
<div class="row text-left">
    <%= link_to job.title, job, class: "col-lg-10 col-12"%>
    <div class="col-lg-2 col-12">[<%= job.publish_date %>]</div>
</div>
<div class="d-flex w-100 text-left">
<%= simple_format(truncate(job.content, length: 200)) %>
</div>
<% end %>
</div>

<br>
<%= paginate @jobs, theme: 'twitter-bootstrap-4' %>
<%= link_to 'New Job', new_job_path, class: "btn btn-primary" %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job, class: "btn btn-primary" %>
<%= link_to 'Back', jobs_path, class: "btn btn-secondary" %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h5 class="d-flex w-100 bg-light p-2" id="job-title"><%= @job.title %></h5>

<p>
  <%= simple_format(@job.content) %>
</p>

<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-primary" %> |
<%= link_to 'Back', jobs_path, class: "btn btn-secondary" %>

app/views/layouts/_footer.html.erb
<footer class="text-center">
  國立臺北商業大學資訊管理系(本校行政大樓四樓) 版權所有<br>
  10051 台北市中正區濟南路一段 321 號 (捷運板南線善導寺站下車)<br>
  Add.: No.321, Sec. 1, Jinan Rd., Zhongzheng District, Taipei City 10051, Taiwan (R.O.C.)<br>
  聯絡電話 886-2-23226408~6413 傳真電話 886-2-23226414<br>
</footer>

app/views/layouts/_header.html.erb
<div class="row" id="top-header">
  <div class="col-lg-9 col-12" id="ip-text">
    給我一個IP ，我給你全世界。
  </div>
  <div class="col-lg-3 col-12 float-right text-right">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Keyword">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary border-0" type="button"></button>
      </div>
    </div>
  </div>
</div>
<header class="row">
  <div class="col-12 text-dark">
    國立臺北商業大學資訊管理系
  </div>
  <div class="col-12">
    <img class="img-fluid" src="http://imd.ntub.edu.tw/ezfiles/34/1034/sys_1034_5236900_56708.png" alt="國立臺北商業大學資訊管理系" border="0">
  </div>
</header>

app/views/layouts/_leftbar.html.erb
<ul class="list-group" id="leftbar">
  <li class="list-group-item" id="leftbar-head">
    <i class="icon ion-arrow-down-b"></i>分類清單</li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        最新消息
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>系科公告</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>活動資訊</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>徵才資訊</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>競賽資訊</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        本系介紹
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>培育目標</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>發展沿革</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>教學特色</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>教學設備</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>English Version</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        師資陣容
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>師資介紹</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>導師名單</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>行政人員</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        課程規劃
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>課程科目表</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>學生課程地圖~課程模組</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>資管系學生能力指標</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>畢業門檻</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>資管講座</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        學生資源
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>學生專題</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>實習專區</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn" data-toggle="dropdown">
        招生資訊
      </button>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        榮譽榜單
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>升學榮譽榜</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>證照榮譽榜</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>競賽榮譽榜</a>
      </div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn" data-toggle="dropdown">
        FAQ
      </button>
    </div>
  </li>
  <li class="list-group-item">
    <div class="dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
        其他資源
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>相關法規</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>行事曆</a>
        <a class="dropdown-item" href="#"><i class="icon ion-arrow-right-c"></i>意見箱</a>
      </div>
    </div>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white px-0 px-lg-3" id="navbar">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">回首頁</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">回北商首頁</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">回管理學院</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">商業智慧研究中心</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">English Version</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NtubImdJob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="container bg-white">
      <%= render "layouts/header" %>
      <%= render "layouts/navbar" %>
      <div class="row">
        <div class="col-lg-2 my-2">
          <%= render "layouts/leftbar" %>
        </div>
        <div class="col-lg-10 my-2">
          <%= yield %>
        </div>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>